name: Secure Python Pipeline

on:
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '0 0 * * 0'  # Run once a week

permissions:
  contents: read

jobs:
  security_checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run SAST with Bandit
      - name: Run SAST with Bandit
        run: |
          pip install bandit
          bandit -r .
        continue-on-error: true
        id: bandit_check

      # Check for vulnerable dependencies with Safety
      - name: Check for vulnerable dependencies with Safety
        run: |
          pip install safety
          safety check
        continue-on-error: true
        id: safety_check

      # Check for secrets with TruffleHog (edplato version)
      - name: Run TruffleHog scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          entryPoint: .  # The root of the repository
          args: "--no-git"  # Additional arguments if needed
        continue-on-error: true
        id: trufflehog_check

      # Fail the PR if any check fails
      - name: Fail the PR if any check fails
        run: |
          if [[ "${{ steps.bandit_check.outcome }}" == "failure" ]]; then
            echo "SAST check (Bandit) failed"
            exit 1
          elif [[ "${{ steps.safety_check.outcome }}" == "failure" ]]; then
            echo "Dependency check (Safety) failed"
            exit 1
          elif [[ "${{ steps.trufflehog_check.outcome }}" == "failure" ]]; then
            echo "Secrets check (TruffleHog) failed"
            exit 1
          fi
          echo "All checks passed"
