# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Secure Python Pipeline

on:
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '0 0 * * 0'  # Run once a week

permissions:
  contents: read

jobs:
  security_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run SAST with Bandit
      run: |
        pip install bandit
        bandit -r . -f html -o bandit-report.html
      continue-on-error: false  # Fail the workflow if this check finds issues

    - name: Check for vulnerable dependencies with Safety
      run: |
        pip install safety
        safety check --full-report --output-file=safety-report.json
      continue-on-error: false  # Fail the workflow if this check finds issues

    - name: Check for secrets with TruffleHog
      uses: trufflesecurity/trufflehog@v3.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Fail the PR if any check fails
      if: failure()  # Fail the PR if any of the above checks failed
      run: |
        echo "One or more security checks failed, please fix them before merging."
        exit 1



