name: Secure Python Pipeline

on:
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '0 0 * * 0'  # Run once a week

permissions:
  contents: read

jobs:
  security_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run SAST with Bandit
      run: |
        pip install bandit
        bandit -r .
      continue-on-error: true
      id: bandit_check

    - name: Check for vulnerable dependencies with Safety
      run: |
        pip install safety
        safety check
      continue-on-error: true
      id: safety_check

    - name: Scan secrets with TruffleHog
      uses: edplato/trufflehog-actions-scan@master
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
      continue-on-error: true
      id: trufflehog_new_check

    - name: Fail the PR if any check fails
      run: |
        if [[ "${{ steps.bandit_check.outcome }}" == "failure" ]]; then
          echo "SAST check failed"
          exit 1
        elif [[ "${{ steps.safety_check.outcome }}" == "failure" ]]; then
          echo "Dependency check failed"
          exit 1
        elif [[ "${{ steps.trufflehog_check.outcome }}" == "failure" ]]; then
          echo "Original TruffleHog scan failed"
          exit 1
        elif [[ "${{ steps.trufflehog_new_check.outcome }}" == "failure" ]]; then
          echo "New TruffleHog scan failed"
          exit 1
        fi
        echo "All checks passed"
