# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Secure Python Pipeline

on:
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '0 0 * * 0'  # Run once a week

permissions:
  contents: read

jobs:
  security_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run SAST with Bandit
      run: |
        pip install bandit
        bandit -r .
      continue-on-error: true
      id: bandit_check

    - name: Check for vulnerable dependencies with Safety
      run: |
        pip install safety
        safety check
      continue-on-error: true
      id: safety_check

    - name: Check for secrets with TruffleHog
      uses: trufflesecurity/trufflehog@v3.0.0
      with:
        entryPoint: .  # Set to the root of your repository
        args: "--no-git"  # Additional arguments if needed
      continue-on-error: true
      id: trufflehog_check


    - name: Fail the PR if any check fails
      run: |
        if [[ "${{ steps.bandit_check.outcome }}" == "failure" ]]; then
          echo "SAST check failed"
          exit 1
        elif [[ "${{ steps.safety_check.outcome }}" == "failure" ]]; then
          echo "Dependency check failed"
          exit 1
        elif [[ "${{ steps.trufflehog_check.outcome }}" == "failure" ]]; then
          echo "Secret scan failed"
          exit 1
        fi
        echo "All checks passed"




